const errorMessages = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MISSING: "MISSING",
  IS_EMPTY: "IS_EMPTY",
  IS_STRING: "IS_NOT_STRING",
  IS_NUMERIC: "IS_NOT_NUMERIC",
  IS_DATE: "IS_NOT_DATE",
  NAME_REQUIRED: "NAME_REQUIRED",
  INVALID_EMAIL: "INVALID_EMAIL",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  ACCESS_TOKEN_REQUIRED: "ACCESS_TOKEN_REQUIRED",
  RESET_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  PAGE_MIN: "PAGE_MIN",
  PER_PAGE_MIN: "PER_PAGE_MIN",
  INVALID_ROLE: "INVALID_ROLE",
  ROLE_REQUIRED: "ROLE_REQUIRED",
  USER_ID_REQUIRED: "USER_ID_REQUIRED",
  NOT_FOUND: "NOT_FOUND"
};

module.exports = { errorMessages };
